# Generated by Django 3.0.4 on 2020-04-06 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(max_length=100, null=True)),
                ('category', models.CharField(choices=[('In', 'Individual'), ('Co', 'Company'), ('Cy', 'Country')], max_length=10)),
                ('product', models.CharField(choices=[('Ag', 'Agricultural'), ('Ho', 'Home'), ('Pe', 'Personal'), ('Ve', 'Vehicle')], max_length=10)),
                ('weightage', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Criteria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(max_length=100, null=True)),
                ('category', models.CharField(max_length=10)),
                ('product', models.CharField(max_length=10)),
                ('data_source', models.CharField(max_length=10)),
                ('api', models.CharField(max_length=10000)),
                ('key', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('value', models.CharField(choices=[('Bi', 'Binary'), ('No', 'Nominal'), ('In', 'Interval'), ('Ra', 'Ratio')], max_length=10)),
                ('data_type', models.CharField(choices=[('Nu', 'Numeric'), ('Ch', 'Character'), ('Da', 'Date')], max_length=10)),
                ('category', models.CharField(choices=[('In', 'Individual'), ('Co', 'Company'), ('Cy', 'Country')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='UploadFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.CharField(default='loan_status', max_length=100)),
                ('columns', models.CharField(max_length=1000000)),
                ('nominal_features', models.CharField(max_length=1000000)),
            ],
        ),
        migrations.CreateModel(
            name='CriteriaHelper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry', models.CharField(max_length=1000000)),
                ('score', models.IntegerField()),
                ('criteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loan_admin.Criteria')),
            ],
        ),
    ]
