# Generated by Django 3.0.4 on 2020-03-29 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(choices=[('1', 'abc')], max_length=10, null=True)),
                ('category', models.CharField(choices=[('In', 'Individual'), ('Co', 'Company'), ('Cy', 'Country')], max_length=10)),
                ('product', models.CharField(choices=[('Ag', 'Agricultural'), ('Ho', 'Home'), ('Pe', 'Personal'), ('Ve', 'Vehicle')], max_length=10)),
                ('weightage', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='CSV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csv', models.FileField(upload_to='profile/%Y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('value', models.CharField(choices=[('Bi', 'Binary'), ('No', 'Nominal'), ('In', 'Interval'), ('Ra', 'Ratio')], max_length=10)),
                ('data_type', models.CharField(choices=[('Nu', 'Numeric'), ('Ch', 'Character'), ('Da', 'Date')], max_length=10)),
                ('category', models.CharField(choices=[('In', 'Individual'), ('Co', 'Company'), ('Cy', 'Country')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='FieldSchema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('data_type', models.CharField(choices=[('character', 'character'), ('text', 'text'), ('integer', 'integer'), ('float', 'float'), ('boolean', 'boolean'), ('date', 'date')], editable=False, max_length=16)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ModelSchema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=32, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
