# Generated by Django 3.0.4 on 2020-04-06 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfile',
            name='target',
            field=models.CharField(default='loan_status', max_length=100),
        ),
    ]
