# Generated by Django 3.0.4 on 2020-04-06 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loan_admin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadfile',
            name='target',
        ),
    ]
