# Generated by Django 3.0.4 on 2020-03-29 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='feature',
            field=models.CharField(choices=[], max_length=10, null=True),
        ),
    ]
