# Generated by Django 3.0.4 on 2020-04-06 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_admin', '0002_remove_uploadfile_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfile',
            name='target',
            field=models.CharField(default='loan_status', max_length=100),
        ),
    ]
