# Generated by Django 3.0.4 on 2020-03-31 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loan_admin', '0003_auto_20200330_1310'),
    ]

    operations = [
        migrations.CreateModel(
            name='Criteria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(max_length=100, null=True)),
                ('category', models.CharField(max_length=10)),
                ('product', models.CharField(max_length=10)),
                ('data_source', models.CharField(max_length=10)),
                ('api', models.CharField(max_length=10000)),
                ('key', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='configuration',
            name='feature',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='feature',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='uploadfile',
            name='file',
            field=models.FileField(upload_to='credit_risk/dataset'),
        ),
        migrations.CreateModel(
            name='CriteriaHelper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry', models.CharField(max_length=1000000)),
                ('score', models.IntegerField()),
                ('criteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loan_admin.Criteria')),
            ],
        ),
    ]
