# Generated by Django 3.0.4 on 2020-03-30 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_officer', '0002_auto_20200330_0603'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedstate',
            name='statandml',
            field=models.CharField(default='false', max_length=10),
        ),
    ]
