# Generated by Django 3.0.4 on 2020-03-30 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_officer', '0004_feature'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='credit_risk/dataset/test_dataset.csv')),
            ],
        ),
        migrations.DeleteModel(
            name='CSV',
        ),
        migrations.DeleteModel(
            name='Feature',
        ),
    ]
