# Generated by Django 3.0.4 on 2020-03-31 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_officer', '0005_auto_20200330_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='file',
            field=models.FileField(upload_to='credit_risk/dataset'),
        ),
    ]
